### ISSUE TITLE
How to return an empty stream?

### ISSUE THREAD

**Issue by xxchan** [taiki-e/futures-async-stream#71]
I want to write something like this
```rust
#[try_stream(boxed, ok = i32, error = Box<dyn std::error::Error>)]
async fn foo(self: Box<Self>) {
    if self.xxx {
        // early exit. return an empty stream
    }

    #[for_await]
    for x in self.child.execute() {
        yield ...;
    }
}
```

Is that possible or do you have any suggestions about alternative ways to write it?

I can write a big `if` wrapping the whole body, but that's a little big ugly.

**Comment by taiki-e** [comment]
`return Ok(());` should work.

**Comment by xxchan** [comment]
Thanks for you prompt answer! Would you think it's worth adding to the doc?

**Comment by taiki-e** [comment]
It seems reasonable to mention it in the doc.

**Comment by xxchan** [comment]
I can help with that
